staticDir = ['static']
baseURL = "https://pierpuce.github.io/wedding/"
RSVP = "https://dislack.com/f/61db623403d0bc348804ef71"
title = "Pierluigi & Sara si sposano!"
languagecode = "en"
author = "Pierluigi Puce"
# copyright = "Copyright © 2008–2019" #supports html markup
paginate = 3
languageCode = "en"
DefaultContentLanguage = "en"
enableInlineShortcodes = true
footnoteReturnLinkContents = "^"
googleAnalytics = "UA-123-45"
disqusShortname = "yourdiscussshortname"
theme = "monopriv"
enableEmoji = true
summaryLength = 20

[params] 
    faviconSizes = [16, 32, 48]
    custom_css = ["css/custom.css"]
    mainSections = ["post"]
    intro = true
    about = "28 Maggio 2022"
    paypalme = "https://paypal.me/pierpuce?country.x=IT&locale.x=it_IT"
    # gitlab = "https://gitlab.com/_pierluigi/wedding"
    email = "pierluigi.puce@protonmail.com"
    # site meta description
    metadesc = "Il sito web del nostro evento, che si terrá il 28 Maggio a Macerata."
    # site meta keywords
    metakeys = "hugo, simple, minimal, bootstrap, blog"
    # enable/disable disqus comments 
    disqus = false 
    # enable/disable google analytics 
    analytics = false

[Permalinks]
    post = "/:filename/"

[params.search] # Site search powered by DuckDuckGo
    enabled = false
    placeholder="Site Search"

[params.hero]
    enabled = true
    img = "img/logo.png"

[params.header]
    favicontrtw = "img/favicon32x32.png"
    faviconsxt = "img/favicon16x16.png"
    favicon = "img/favicon.ico"
